replicaCount: 2

service:
  targetPort: 5000

ingress:
  enabled: true
  hosts:
    - jupyter-notebook-service.server-tig.prod.corp.mongodb.com

env:
  APP_MESSAGE: Hello from your Flask app!
  GUNICORN_CMD_ARGS: --workers=3 --worker-class=gevent --bind=0.0.0.0:5000 --chdir /app/server --timeout=3600 --access-logfile=- --log-level=DEBUG --config gunicorn_conf.py
  prometheus_multiproc_dir: /tmp/prometheus_multiproc

#envSecrets:
#  APP_SECRET: jupyter-notebook-service-secrets

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 192Mi

metrics:
  enabled: true

prometheusRules:
  # Alert for any instance that has a median request latency >8s.
  - alert: HTTPRequestsLatency8s
    expr: histogram_quantile(0.9, rate(http_request_latency_seconds_bucket{job="jupyter-notebook-service-web-app"}[5m])) > 8
    for: 5m
    labels:
      email_to: corps@mongodb.com
      severity: warning
    annotations:
      description: Service {{ $labels.job }} has a 90th percentile latency higher than 8s.
      summary: High latency on {{ $labels.job }}
